### PR TITLE
Bump bs-platform from 5.0.4 to 7.0.1

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by MoOx** [comment]
I guess starting from here is a good idea as this projet is "no big deal" regarding "production ready" level 😂

**Comment by MoOx** [comment]
Thanks you!

**Comment by cknitt** [comment]
yarn.lock now shows both 5.0.6 and 7.0.1 being installed?

**Comment by MoOx** [comment]
because of reason-react or something like that?

**Comment by imbsky** [comment]
Yes, probably.

**Pull request merged**
